export const POLAND_CROSS_CONFIG_MAP = {
  A: {
    type: 'square',
    leftLine: false,
    rightLine: true,
    topLine: false,
    bottomLine: true,
    dot: false,
  },
  B: {
    type: 'square',
    leftLine: true,
    rightLine: true,
    topLine: false,
    bottomLine: true,
    dot: false,
  },
  C: {
    type: 'square',
    leftLine: false,
    rightLine: true,
    topLine: true,
    bottomLine: true,
    dot: false,
  },
  D: {
    type: 'square',
    leftLine: false,
    rightLine: true,
    topLine: true,
    bottomLine: true,
    dot: false,
  },
  E: {
    type: 'square',
    leftLine: true,
    rightLine: true,
    topLine: true,
    bottomLine: true,
    dot: false,
  },
  F: {
    type: 'square',
    leftLine: true,
    rightLine: false,
    topLine: true,
    bottomLine: true,
    dot: false,
  },
  G: {
    type: 'square',
    leftLine: false,
    rightLine: true,
    topLine: true,
    bottomLine: false,
    dot: false,
  },
  H: {
    type: 'square',
    leftLine: true,
    rightLine: true,
    topLine: true,
    bottomLine: false,
    dot: false,
  },
  I: {
    type: 'square',
    leftLine: true,
    rightLine: false,
    topLine: true,
    bottomLine: false,
    dot: false,
  },
  // dot square
  J: {
    type: 'square',
    leftLine: false,
    rightLine: true,
    topLine: false,
    bottomLine: true,
    dot: true,
  },
  K: {
    type: 'square',
    leftLine: true,
    rightLine: true,
    topLine: false,
    bottomLine: true,
    dot: true,
  },
  // next type
  L: {
    type: 'square',
    leftLine: true,
    rightLine: false,
    topLine: false,
    bottomLine: true,
    dot: true,
  },
  M: {
    type: 'square',
    leftLine: false,
    rightLine: true,
    topLine: true,
    bottomLine: true,
    dot: true,
  },
  N: {
    type: 'square',
    leftLine: true,
    rightLine: true,
    topLine: true,
    bottomLine: true,
    dot: true,
  },
  // next type
  O: {
    type: 'square',
    leftLine: true,
    rightLine: false,
    topLine: true,
    bottomLine: true,
    dot: true,
  },
  P: {
    type: 'square',
    leftLine: false,
    rightLine: true,
    topLine: true,
    bottomLine: false,
    dot: true,
  },
  Q: {
    type: 'square',
    leftLine: true,
    rightLine: true,
    topLine: true,
    bottomLine: false,
    dot: true,
  },
  R: {
    type: 'square',
    leftLine: true,
    rightLine: false,
    topLine: true,
    bottomLine: false,
    dot: true,
  },
  // rhombus without dot
  S: {
    type: 'rhombus',
    line: 'top',
    dot: false,
  },
  T: {
    type: 'rhombus',
    line: 'right',
    dot: false,
  },
  U: {
    type: 'rhombus',
    line: 'bottom',
    dot: false,
  },
  V: {
    type: 'rhombus',
    line: 'left',
    dot: false,
  },
  // rhombus with dot
  W: {
    type: 'rhombus',
    line: 'top',
    dot: true,
  },
  X: {
    type: 'rhombus',
    line: 'right',
    dot: true,
  },
  Y: {
    type: 'rhombus',
    line: 'bottom',
    dot: true,
  },
  Z: {
    type: 'rhombus',
    line: 'left',
    dot: true,
  },
};
