export const HEBREW_CROSS_CONFIG_MAP = {
  A: {
    leftLine: false,
    rightLine: true,
    topLine: false,
    bottomLine: true,
    dotCount: 0,
  },
  B: {
    leftLine: true,
    rightLine: true,
    topLine: false,
    bottomLine: true,
    dotCount: 0,
  },
  C: {
    leftLine: true,
    rightLine: false,
    topLine: false,
    bottomLine: true,
    dotCount: 0,
  },
  D: {
    leftLine: false,
    rightLine: true,
    topLine: true,
    bottomLine: true,
    dotCount: 0,
  },
  E: {
    leftLine: true,
    rightLine: true,
    topLine: true,
    bottomLine: true,
    dotCount: 0,
  },
  F: {
    leftLine: true,
    rightLine: false,
    topLine: true,
    bottomLine: true,
    dotCount: 0,
  },
  G: {
    leftLine: false,
    rightLine: true,
    topLine: true,
    bottomLine: false,
    dotCount: 0,
  },
  H: {
    leftLine: true,
    rightLine: true,
    topLine: true,
    bottomLine: false,
    dotCount: 0,
  },
  CH: {
    leftLine: true,
    rightLine: false,
    topLine: true,
    bottomLine: false,
    dotCount: 0,
  },
  // Dots 1
  I: {
    leftLine: false,
    rightLine: true,
    topLine: false,
    bottomLine: true,
    dotCount: 1,
  },
  J: {
    leftLine: true,
    rightLine: true,
    topLine: false,
    bottomLine: true,
    dotCount: 1,
  },
  K: {
    leftLine: true,
    rightLine: false,
    topLine: false,
    bottomLine: true,
    dotCount: 1,
  },
  L: {
    leftLine: false,
    rightLine: true,
    topLine: true,
    bottomLine: true,
    dotCount: 1,
  },
  M: {
    leftLine: true,
    rightLine: true,
    topLine: true,
    bottomLine: true,
    dotCount: 1,
  },
  N: {
    leftLine: true,
    rightLine: false,
    topLine: true,
    bottomLine: true,
    dotCount: 1,
  },
  O: {
    leftLine: false,
    rightLine: true,
    topLine: true,
    bottomLine: false,
    dotCount: 1,
  },
  P: {
    leftLine: true,
    rightLine: true,
    topLine: true,
    bottomLine: false,
    dotCount: 1,
  },
  Q: {
    leftLine: true,
    rightLine: false,
    topLine: true,
    bottomLine: false,
    dotCount: 1,
  },
  // Dots 2
  R: {
    leftLine: false,
    rightLine: true,
    topLine: false,
    bottomLine: true,
    dotCount: 2,
  },
  S: {
    leftLine: true,
    rightLine: true,
    topLine: false,
    bottomLine: true,
    dotCount: 2,
  },
  T: {
    leftLine: true,
    rightLine: false,
    topLine: false,
    bottomLine: true,
    dotCount: 2,
  },
  U: {
    leftLine: false,
    rightLine: true,
    topLine: true,
    bottomLine: true,
    dotCount: 2,
  },
  V: {
    leftLine: true,
    rightLine: true,
    topLine: true,
    bottomLine: true,
    dotCount: 2,
  },
  W: {
    leftLine: true,
    rightLine: false,
    topLine: true,
    bottomLine: true,
    dotCount: 2,
  },
  X: {
    leftLine: false,
    rightLine: true,
    topLine: true,
    bottomLine: false,
    dotCount: 2,
  },
  Y: {
    leftLine: true,
    rightLine: true,
    topLine: true,
    bottomLine: false,
    dotCount: 2,
  },
  Z: {
    leftLine: true,
    rightLine: false,
    topLine: true,
    bottomLine: false,
    dotCount: 2,
  },
};
