export const DIFFERENT_CROSS_CONFIG_MAP = {
  A: {
    type: 'ThreeRectangle',
    leftLine: false,
    rightLine: true,
    topLine: false,
    bottomLine: true,
    dotPosition: 0,
  },
  B: {
    type: 'ThreeRectangle',
    leftLine: false,
    rightLine: true,
    topLine: false,
    bottomLine: true,
    dotPosition: 1,
  },
  C: {
    type: 'ThreeRectangle',
    leftLine: false,
    rightLine: true,
    topLine: false,
    bottomLine: true,
    dotPosition: 2,
  },
  // next type
  D: {
    type: 'TwoRectangle',
    leftLine: true,
    rightLine: true,
    topLine: false,
    bottomLine: true,
    dotPosition: 0,
    special: 'DoubleRight',
  },
  E: {
    type: 'TwoRectangle',
    leftLine: true,
    rightLine: true,
    topLine: false,
    bottomLine: true,
    dotPosition: 1,
    special: 'DoubleRight',
  },
  // next type
  F: {
    type: 'TwoRectangle',
    leftLine: true,
    rightLine: true,
    topLine: false,
    bottomLine: true,
    dotPosition: 0,
    special: 'DoubleLeft',
  },
  G: {
    type: 'TwoRectangle',
    leftLine: true,
    rightLine: true,
    topLine: false,
    bottomLine: true,
    dotPosition: 1,
    special: 'DoubleLeft',
  },
  // next type
  H: {
    type: 'TwoRectangle',
    leftLine: true,
    rightLine: false,
    topLine: false,
    bottomLine: true,
    dotPosition: 0,
    special: 'None',
  },
  CH: {
    type: 'TwoRectangle',
    leftLine: true,
    rightLine: false,
    topLine: false,
    bottomLine: true,
    dotPosition: 1,
    special: 'None',
  },
  // next type
  I: {
    type: 'ThreeRectangle',
    leftLine: false,
    rightLine: true,
    topLine: true,
    bottomLine: true,
    dotPosition: 0,
  },
  J: {
    type: 'ThreeRectangle',
    leftLine: false,
    rightLine: true,
    topLine: true,
    bottomLine: true,
    dotPosition: 1,
  },
  K: {
    type: 'ThreeRectangle',
    leftLine: false,
    rightLine: true,
    topLine: true,
    bottomLine: true,
    dotPosition: 2,
  },
  // next type
  L: {
    type: 'TwoRectangle',
    leftLine: true,
    rightLine: true,
    topLine: true,
    bottomLine: true,
    dotPosition: 0,
    special: 'DoubleRight',
  },
  M: {
    type: 'TwoRectangle',
    leftLine: true,
    rightLine: true,
    topLine: true,
    bottomLine: true,
    dotPosition: 1,
    special: 'DoubleRight',
  },
  // next type
  N: {
    type: 'TwoRectangle',
    leftLine: true,
    rightLine: true,
    topLine: true,
    bottomLine: true,
    dotPosition: 0,
    special: 'DoubleLeft',
  },
  O: {
    type: 'TwoRectangle',
    leftLine: true,
    rightLine: true,
    topLine: true,
    bottomLine: true,
    dotPosition: 1,
    special: 'DoubleRight',
  },
  // next type
  P: {
    type: 'TwoRectangle',
    leftLine: true,
    rightLine: false,
    topLine: true,
    bottomLine: true,
    dotPosition: 0,
    special: 'None',
  },
  Q: {
    type: 'TwoRectangle',
    leftLine: true,
    rightLine: false,
    topLine: true,
    bottomLine: true,
    dotPosition: 1,
    special: 'None',
  },
  // new row
  R: {
    type: 'ThreeRectangle',
    leftLine: false,
    rightLine: true,
    topLine: true,
    bottomLine: false,
    dotPosition: 0,
  },
  S: {
    type: 'ThreeRectangle',
    leftLine: false,
    rightLine: true,
    topLine: true,
    bottomLine: false,
    dotPosition: 1,
  },
  T: {
    type: 'ThreeRectangle',
    leftLine: false,
    rightLine: true,
    topLine: true,
    bottomLine: false,
    dotPosition: 3,
  },
  // next type
  U: {
    type: 'TwoRectangle',
    leftLine: true,
    rightLine: true,
    topLine: true,
    bottomLine: false,
    dotPosition: 0,
    special: 'DoubleRight',
  },
  V: {
    type: 'TwoRectangle',
    leftLine: true,
    rightLine: true,
    topLine: true,
    bottomLine: false,
    dotPosition: 1,
    special: 'DoubleRight',
  },
  // next type
  W: {
    type: 'TwoRectangle',
    leftLine: true,
    rightLine: true,
    topLine: true,
    bottomLine: false,
    dotPosition: 0,
    special: 'DoubleLeft',
  },
  X: {
    type: 'TwoRectangle',
    leftLine: true,
    rightLine: true,
    topLine: true,
    bottomLine: false,
    dotPosition: 1,
    special: 'DoubleLeft',
  },
  // next type
  Y: {
    type: 'TwoRectangle',
    leftLine: true,
    rightLine: false,
    topLine: true,
    bottomLine: false,
    dotPosition: 0,
    special: 'None',
  },
  Z: {
    type: 'TwoRectangle',
    leftLine: true,
    rightLine: false,
    topLine: true,
    bottomLine: false,
    dotPosition: 1,
    special: 'None',
  },
};
