import fs from 'fs';
import path from 'path';

export function generateGlyphs(svgFiles, startCode = 100) {
  const glyphs = {};
  let currentCode = startCode;

  svgFiles.forEach((file) => {
    const filename = path
      .basename(file, '.svg')
      .toUpperCase()
      .replace(/\W+/g, '_');
    glyphs[filename] = currentCode.toString(16);
    currentCode++;
  });

  return glyphs;
}

export function writeJSGlyphsFile(glyphs, outputPath, fontName) {
  const entries = Object.entries(glyphs)
    .map(([key, code]) => `  ${key}: '\\u{${code}}'`)
    .join(',\n');

  let content = '// Auto-generated by generate-font\n';
  content += `const ${fontName}Glyphs = Object.freeze({\n${entries}\n});\n`;
  content += 'module.exports = { KidscipherGlyphs };\n';

  fs.writeFileSync(outputPath, content, 'utf-8');
  return outputPath;
}
